# ===================================================================
# This Docker Compose file is configured for a production environment
# -------------------------------------------------------------------
version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - cosmic_defender_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    command: ["sh", "-c", "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p ${WEB_PORT_INTERNAL} -b '0.0.0.0'"]
    volumes:
      - .:/var/www/CosmicDefender
    ports:
      - "${WEB_PORT_EXTERNAL}:${WEB_PORT_INTERNAL}"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RAILS_ENV: production
      RACK_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/CosmicDefender_production"
      GAME_API_PORT: ${GAME_API_PORT}

volumes:
  cosmic_defender_pg_data:
