default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CosmicDefender_development
test:
  <<: *default
  database: CosmicDefender_test

production:
  <<: *default
  database: CosmicDefender_production
  username: CosmicDefender
  password: <%= ENV["COSMICDEFENDER_DATABASE_PASSWORD"] %>


#####################################################################
## DOCKER CONFIG #########
##########################
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  # For details on connection pooling, see Rails configuration guide
#  # https://guides.rubyonrails.org/configuring.html#database-pooling
#  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  url: <%#= ENV['DATABASE_URL'] %>

#production:
#  <<: *default
#  database: CosmicDefender_production
#  username: postgres  # Changed to match the default PostgreSQL username
#  password: <%#= ENV["POSTGRES_PASSWORD"] %>  # Changed to match the environment variable
#  host: db  # This should match the service name in docker-compose.yml
#  port: 5432  # Default PostgreSQL port

#development:
#  <<: *default
#  database: CosmicDefender_development
#  username: postgres  # Changed to match the default PostgreSQL username
#  password: <%#= ENV["POSTGRES_PASSWORD"] %>  # Changed to match the environment variable
#  host: db  # This should match the service name in docker-compose.yml
#  port: 5432  # Default PostgreSQL port
